[package]
name           = "sansan"
version        = "0.0.0"
edition        = "2021"
authors        = ["hinto.janai <hinto.janai@protonmail.com>"]
homepage       = "https://sansan.cat"
documentation  = "https://docs.rs/sansan"
repository     = "https://github.com/hinto-janai/sansan"
keywords       = ["music", "playback", "audio", "metadata"]
categories     = ["multimedia"]
readme         = "README.md"
license        = "MIT"
description    = "Audio playback library"
#rust-version   = "1.70"


[profile.release]
strip         = "none"
lto           = true
codegen-units = 1

[package.metadata.docs.rs]
all-features = true

[dependencies]

