name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: 8000000

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          target
          ~/.cargo
        key: ${{ matrix.os }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == 'Linux' ]; then
          sudo apt update
          sudo apt install -y libasound2-dev libpulse-dev libdbus-1-dev
        fi
        rustup toolchain add 1.70.0 --profile default
        cargo install cargo-deny
        cargo install cargo-audit

    - name: Deny
      run: cargo deny check

    - name: Audit
      shell: bash
      run: |
        rm -rf ~/.cargo/advisory-db
        cargo audit

    - name: Clippy
      shell: bash
      run: cargo +1.70.0 clippy

    - name: Test
      shell: bash
      run: cargo +1.70.0 test
