# This documents everything, but not the dependencies.

name: Doc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: doc
    - uses: actions/checkout@v3
      with:
        submodules: recursive
#    - name: Install dependencies
#      run: |
#        sudo apt update
#        sudo apt install -y libgtk-3-dev
    - name: Doc
      run: cargo doc --workspace --no-deps --all-features
