# Attempt downloading all files from `sansan.cat`
# and verifies the SHA256SUMS & PGP signature.

name: Download
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Windows
      run: wget --content-disposition "https://sansan.cat/${{ matrix.pkg }}-windows-x64"
    - name: Download macOS
      run: wget --content-disposition "https://sansan.cat/${{ matrix.pkg }}-macos-x64" "https://sansan.cat/${{ matrix.pkg }}-macos-arm64"
    - name: Download Linux
      run: wget --content-disposition "https://sansan.cat/${{ matrix.pkg }}-linux-x64"
    - name: Download Hashes
      run: wget "https://sansan.cat/hashes-${{ matrix.pkg }}"
    - name: Download PGP key
      run: wget "https://pgp.sansan.cat" -O hinto-janai.txt
    - name: Verify PGP key
      run: bash -c "[[ $(sha256sum "hinto-janai.txt" | awk '{print $1}') == 02242a2c4b4dfb2f49d30a15630a301c72910e6e5c212d432c8b7ff438696b00 ]]"
    - name: Import PGP key
      run: gpg --import hinto-janai.txt
    - name: Verify Hashes
      run: sha256sum -c "hashes-${{ matrix.pkg }}"
    - name: Verify PGP Signature
      run: gpg --verify "hashes-${{ matrix.pkg }}"
    - name: Download Hashes (GitHub)
      run: |
        VERSION=$(grep -m1 "version" Cargo.toml | grep -o "[0-9].[0-9].[0-9]")
        wget --content-disposition "https://github.com/hinto-janai/sansan/releases/download/v${VERSION}/SHA256SUMS"
    - name: Verify Hashes (GitHub)
      run: sha256sum -c SHA256SUMS
    - name: Verify PGP Signature (GitHub)
      run: gpg --verify SHA256SUMS
